### ISSUE TITLE
Brrl command not found

### ISSUE THREAD

**Issue by JonHendershot** [barrel/barrel-cli#1]
After running `npm i` (where barrel cli is in package.json), I'm getting a `bash: brrl: command not found` error. Tried reinstalling with `npm i barrel-cli -D` and got a 404 error. Using https://registry.npmjs.org/ as base registry. Also tried installing with `npm install @barrelny/cli` as per https://www.npmjs.com/package/@barrelny/cli -- no luck. Looks like the issue may be around the "bin" field in the package.json.

**Comment by maxrolon** [comment]
@JonHendershot Yo! The 'brrl' command can be used in npm scripts as the npm script knows to look for commands in npm_modules/.bin folder, whereas as the current shell does not. I'll look to see if there is a better way to allow commands to be globally called, when they are installed in local projects.

**Comment by wturnerharris** [comment]
I think you can only run that command when it's installed globally. There is a better way—[`npx`](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b).

I can run `npx brrl -w` without issue.
