### ISSUE TITLE
-bash: brrl: command not found

### ISSUE THREAD

**Issue by wilbunge** [barrel/barrel-cli#6]
Hi,

After running "npm i @barrelny/cli -D", I try to run "brrl -b" and get the error:

-bash: brrl: command not found

Any clues?

Thanks,
Wil

**Comment by wturnerharris** [comment]
@wilbunge please report your operating system, node, and npm versions.

**Comment by wilbunge** [comment]
Thanks Wes, here it goes:

System Version = macOS 10.13.6 (17G65)
node -v = v10.1.0
npm -v = 5.6.0

**Comment by wturnerharris** [comment]
@wilbunge can you run either `npx brrl -b` or make sure you have an entry of `brrl -b -e production` under "build" within "scripts" property of package.json. Then try running `npm run build`

**Comment by wilbunge** [comment]
Txs Wes.


npx brrl -b:


node[49416]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::InternalCallbackScope::~InternalCallbackScope() [/usr/local/bin/node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x38af1570427d
 8: 0x38af1570f755
 9: 0x38af1578bc20
10: 0x38af157144f7
11: 0x38af157144f7
Abort trap: 6




These are my package.json contents: 

{
  "name": "barrel-base",
  "version": "1.6.0",
  "scripts": {
    "start": "brrl -w",
    "build": "brrl -b -e production; npm run critical",
    "critical": "postcss src/css/main.css -o assets/critical.min.css --config tasks/"
  },
  "devDependencies": {
    "@barrelny/cli": "0.0.19",
    "dom-event": "^1.0.0",
    "layzr.js": "^2.2.2",
    "postcss-cli": "^5.0.1",
    "postcss-critical-split": "^2.5.1",
    "cssnano": "^3.10.0"
  }
}

**Comment by maxrolon** [comment]
@wilbunge ` ../src/node_contextify.cc:628:static void node::contextify::ContextifyScrip...` is a super annoying error that usually has an easy solve. Remove your package-lock and node_modules and `npm i` again. This is not an issue with the barrel-cli, but an issue with upgrading node/npm

As to `brrl: command not found`, I have noticed that npm removes existing .bin bindings when you install new packages. Running `npm i` should set up these .bin bindings again and fix this issue.

**Comment by wilbunge** [comment]
Thanks Max!
